### ISSUE TITLE
patch -Np1 -i ~/Xavier-KVM/patches/kernel/*.patch FAILED

### ISSUE THREAD

**Issue by outbackdingo** [b-man/Xavier-KVM#3]
cd hardware/
dingo@dingo-Xavier:~/Linux_for_Tegra/source/public/hardware$ patch -Np1 -i ~/Xavier-KVM/patches/hardware/0001-Enable-KVM-support-for-t194.patch
patching file nvidia/soc/t19x/kernel-dts/tegra194-soc/tegra194-soc-base.dtsi
dingo@dingo-Xavier:~/Linux_for_Tegra/source/public/hardware$ patch -Np1 -i ~/Xavier-KVM/patches/kernel/*.patch
patching file /home/dingo/Xavier-KVM/patches/kernel/0002-KVM-ARM64-fix-phy-counter-access-failure-in-guest.patch
Hunk #1 FAILED at 33.
1 out of 1 hunk FAILED -- saving rejects to file /home/dingo/Xavier-KVM/patches/kernel/0002-KVM-ARM64-fix-phy-counter-access-failure-in-guest.patch.rej
dingo@dingo-Xavier:~/Linux_for_Tegra/source/public/hardware$ cat /home/dingo/Xavier-KVM/patches/kernel/0002-KVM-ARM64-fix-phy-counter-access-failure-in-guest.patch.rej
--- drivers/base/regmap/regcache-rbtree.c
+++ drivers/base/regmap/regcache-rbtree.c
@@ -33,7 +33,7 @@ struct regcache_rbtree_node {
 	unsigned int blklen;
 	/* the actual rbtree node holding this block */
 	struct rb_node node;
-} __attribute__ ((packed));
+};
 
 struct regcache_rbtree_ctx {
 	struct rb_root root;

**Comment by b-man** [comment]
@outbackdingo 
I updated the instructions to avoid giving the patch command wildcards directly.
Does this change work for you?

**Comment by outbackdingo** [comment]
looks good to me!
